apiVersion: apps/v1
kind: Deployment
metadata:
  name: aynaapigateway
spec:
  replicas: 1  # Number of instances (pods) to run
  selector:
    matchLabels:
      app: aynaapigateway
  template:
    metadata:
      labels:
        app: aynaapigateway
    spec:
      containers:
      - name: aynaapigateway
        image: ganesh2soft/aynaapigateway:latest # Replace with your Docker image name
        imagePullPolicy: IfNotPresent  
        
        ports:
        - containerPort: 9200  # Port that your Spring Boot application listens on inside the container
