                        FROM eclipse-temurin:latest
						
						RUN pwd
						
						RUN ls -al
						
						RUN dir
						
						COPY  target/aynaapigateway-0.0.1-SNAPSHOT.jar /aynaapigateway/aynaapigateway.jar
						
						WORKDIR /aynaapigateway
						
						RUN pwd
						
						RUN ls -al
                                             
                       
						
						
                        CMD ["java", "-jar", "aynaapigateway.jar"]
                    