apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlhost
  labels:
    app: mysqlhost
    tier: database
spec:
  selector: # mysql Pod Should contain same labels 
    matchLabels:
      app: mysqlhost
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: mysqlhost
        tier: database
    spec:
      containers:
        - name: mysqlhost 
          image: mysql:8.4 # image from docker-hub
#        args:
#          - "--ignore-db-dir=lost+found" # Workaround for https://github.com/docker-library/mysql/issues/186
        
          env:
           - name: MYSQL_ROOT_PASSWORD # Setting Root Password of mysql From a 'Secret'
             valueFrom:
              secretKeyRef:
                name: mysqlhost-root-credentials # Name of the 'Secret'
                key: password   # 'key' inside the Secret which contains required 'value'
        
           
           - name: MYSQL_HOST # Setting Host from a 'ConfigMap'
             valueFrom:
              configMapKeyRef:
                name: mysqlhost-db-conf
                key: host
          ports:
           - containerPort: 3306
              
          volumeMounts:        # Mounting voulume obtained from Persistent Volume Claim
           - name: mysql-persistent-storage
             mountPath: /var/lib/mysql #This is the path in the container on which the mounting will take place.
      volumes:
        - name: mysql-persistent-storage # Obtaining 'vloume' from PVC
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      