apiVersion: apps/v1
kind: Deployment
metadata:
  name: aynaorder
spec:
  replicas: 1  # Number of instances (pods) to run
  selector:
    matchLabels:
      app: aynaorder
  template:
    metadata:
      labels:
        app: aynaorder
    spec:
      containers:
      - name: aynaorder
        image: ganesh2soft/aynaorder:latest # Replace with your Docker image name
        imagePullPolicy: IfNotPresent  
        
        ports:
        - containerPort: 9105  # Port that your Spring Boot application listens on inside the container
