apiVersion: v1
kind: ConfigMap
metadata:
  name: aynastock-db-conf
data:
 host: mysql
 name: stockdb
 init.sql: |
    CREATE DATABASE IF NOT EXISTS orderdb;
    CREATE DATABASE IF NOT EXISTS paymentdb;
    CREATE DATABASE IF NOT EXISTS productdb;