apiVersion: apps/v1
kind: Deployment
metadata:
  name: aynaproduct
spec:
  replicas: 1  # Number of instances (pods) to run
  selector:
    matchLabels:
      app: aynaproduct
  template:
    metadata:
      labels:
        app: aynaproduct
    spec:
      containers:
      - name: aynaproduct
        image: ganesh2soft/aynaproduct:latest # Replace with your Docker image name
        imagePullPolicy: IfNotPresent  
        
        ports:
        - containerPort: 9100  # Port that your Spring Boot application listens on inside the container
