apiVersion: v1
kind: Service
metadata:
  name: aynaproduct
spec:
  selector:
    app: aynaproduct  # Must match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80  # Service port (port exposed on the Service)
      targetPort: 9100  # Port your application is listening on inside the container
      nodePort: 30010  # NodePort number (replace with your desired port number)
  type: NodePort  # Expose the Service on a NodePort
